#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1stpage
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="user_info")]
	public partial class ORMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser_info(User_info instance);
    partial void UpdateUser_info(User_info instance);
    partial void DeleteUser_info(User_info instance);
    partial void InsertHostel_find(Hostel_find instance);
    partial void UpdateHostel_find(Hostel_find instance);
    partial void DeleteHostel_find(Hostel_find instance);
    partial void InsertCost_info(Cost_info instance);
    partial void UpdateCost_info(Cost_info instance);
    partial void DeleteCost_info(Cost_info instance);
    partial void InsertVerification_table(Verification_table instance);
    partial void UpdateVerification_table(Verification_table instance);
    partial void DeleteVerification_table(Verification_table instance);
    #endregion
		
		public ORMDataContext() : 
				base(global::_1stpage.Properties.Settings.Default.user_infoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ORMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ORMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ORMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ORMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User_info> User_infos
		{
			get
			{
				return this.GetTable<User_info>();
			}
		}
		
		public System.Data.Linq.Table<Hostel_find> Hostel_finds
		{
			get
			{
				return this.GetTable<Hostel_find>();
			}
		}
		
		public System.Data.Linq.Table<Cost_info> Cost_infos
		{
			get
			{
				return this.GetTable<Cost_info>();
			}
		}
		
		public System.Data.Linq.Table<Verification_table> Verification_tables
		{
			get
			{
				return this.GetTable<Verification_table>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Table]")]
	public partial class User_info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _First_name;
		
		private string _Last_name;
		
		private string _E_mail;
		
		private string _Password;
		
		private string _DOB;
		
		private string _Account_type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFirst_nameChanging(string value);
    partial void OnFirst_nameChanged();
    partial void OnLast_nameChanging(string value);
    partial void OnLast_nameChanged();
    partial void OnE_mailChanging(string value);
    partial void OnE_mailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnDOBChanging(string value);
    partial void OnDOBChanged();
    partial void OnAccount_typeChanging(string value);
    partial void OnAccount_typeChanged();
    #endregion
		
		public User_info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[First name]", Storage="_First_name", DbType="VarChar(50)")]
		public string First_name
		{
			get
			{
				return this._First_name;
			}
			set
			{
				if ((this._First_name != value))
				{
					this.OnFirst_nameChanging(value);
					this.SendPropertyChanging();
					this._First_name = value;
					this.SendPropertyChanged("First_name");
					this.OnFirst_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last name]", Storage="_Last_name", DbType="VarChar(50)")]
		public string Last_name
		{
			get
			{
				return this._Last_name;
			}
			set
			{
				if ((this._Last_name != value))
				{
					this.OnLast_nameChanging(value);
					this.SendPropertyChanging();
					this._Last_name = value;
					this.SendPropertyChanged("Last_name");
					this.OnLast_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[E-mail]", Storage="_E_mail", DbType="VarChar(50)")]
		public string E_mail
		{
			get
			{
				return this._E_mail;
			}
			set
			{
				if ((this._E_mail != value))
				{
					this.OnE_mailChanging(value);
					this.SendPropertyChanging();
					this._E_mail = value;
					this.SendPropertyChanged("E_mail");
					this.OnE_mailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="VarChar(50)")]
		public string DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Account_type
		{
			get
			{
				return this._Account_type;
			}
			set
			{
				if ((this._Account_type != value))
				{
					this.OnAccount_typeChanging(value);
					this.SendPropertyChanging();
					this._Account_type = value;
					this.SendPropertyChanged("Account_type");
					this.OnAccount_typeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hostel_find")]
	public partial class Hostel_find : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _H_name;
		
		private string _A_name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnH_nameChanging(string value);
    partial void OnH_nameChanged();
    partial void OnA_nameChanging(string value);
    partial void OnA_nameChanged();
    #endregion
		
		public Hostel_find()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_H_name", DbType="VarChar(50)")]
		public string H_name
		{
			get
			{
				return this._H_name;
			}
			set
			{
				if ((this._H_name != value))
				{
					this.OnH_nameChanging(value);
					this.SendPropertyChanging();
					this._H_name = value;
					this.SendPropertyChanged("H_name");
					this.OnH_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_name", DbType="VarChar(50)")]
		public string A_name
		{
			get
			{
				return this._A_name;
			}
			set
			{
				if ((this._A_name != value))
				{
					this.OnA_nameChanging(value);
					this.SendPropertyChanging();
					this._A_name = value;
					this.SendPropertyChanged("A_name");
					this.OnA_nameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cost_info")]
	public partial class Cost_info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _name;
		
		private string _CostA;
		
		private string _CostB;
		
		private string _CostC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnCostAChanging(string value);
    partial void OnCostAChanged();
    partial void OnCostBChanging(string value);
    partial void OnCostBChanged();
    partial void OnCostCChanging(string value);
    partial void OnCostCChanged();
    #endregion
		
		public Cost_info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostA", DbType="VarChar(50)")]
		public string CostA
		{
			get
			{
				return this._CostA;
			}
			set
			{
				if ((this._CostA != value))
				{
					this.OnCostAChanging(value);
					this.SendPropertyChanging();
					this._CostA = value;
					this.SendPropertyChanged("CostA");
					this.OnCostAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostB", DbType="VarChar(50)")]
		public string CostB
		{
			get
			{
				return this._CostB;
			}
			set
			{
				if ((this._CostB != value))
				{
					this.OnCostBChanging(value);
					this.SendPropertyChanging();
					this._CostB = value;
					this.SendPropertyChanged("CostB");
					this.OnCostBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostC", DbType="VarChar(50)")]
		public string CostC
		{
			get
			{
				return this._CostC;
			}
			set
			{
				if ((this._CostC != value))
				{
					this.OnCostCChanging(value);
					this.SendPropertyChanging();
					this._CostC = value;
					this.SendPropertyChanged("CostC");
					this.OnCostCChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Verification_table")]
	public partial class Verification_table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Login_name;
		
		private string _Hostel_name;
		
		private string _Verifi_status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnLogin_nameChanging(string value);
    partial void OnLogin_nameChanged();
    partial void OnHostel_nameChanging(string value);
    partial void OnHostel_nameChanged();
    partial void OnVerifi_statusChanging(string value);
    partial void OnVerifi_statusChanged();
    #endregion
		
		public Verification_table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login_name", DbType="VarChar(50)")]
		public string Login_name
		{
			get
			{
				return this._Login_name;
			}
			set
			{
				if ((this._Login_name != value))
				{
					this.OnLogin_nameChanging(value);
					this.SendPropertyChanging();
					this._Login_name = value;
					this.SendPropertyChanged("Login_name");
					this.OnLogin_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hostel_name", DbType="VarChar(50)")]
		public string Hostel_name
		{
			get
			{
				return this._Hostel_name;
			}
			set
			{
				if ((this._Hostel_name != value))
				{
					this.OnHostel_nameChanging(value);
					this.SendPropertyChanging();
					this._Hostel_name = value;
					this.SendPropertyChanged("Hostel_name");
					this.OnHostel_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Verifi_status", DbType="VarChar(50)")]
		public string Verifi_status
		{
			get
			{
				return this._Verifi_status;
			}
			set
			{
				if ((this._Verifi_status != value))
				{
					this.OnVerifi_statusChanging(value);
					this.SendPropertyChanging();
					this._Verifi_status = value;
					this.SendPropertyChanged("Verifi_status");
					this.OnVerifi_statusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
